### ISSUE TITLE
Tpl: inccorect highlighting "for" when a substring of different tag

### ISSUE THREAD

**Issue by jdufresne** [davidmiller/pony-mode#80]
Test case:

```
{% form_tag foo %}
```

In the test case above the "for" substring of "form_tag" is highlighted as if the template is using the "for" template tag.

Pony mode was installed through package.el, version: 20140127.846

**Comment by mrkkrp** [comment]
The same thing here. Is it ignored and won't be fixed or what?

**Comment by davidmiller** [comment]
Hi both - thanks for the bump @mrkkrp this is now fixed on master with https://github.com/davidmiller/pony-mode/commit/7c632ad58bc086c989184443228dfed4d141f1da

**Comment by jdufresne** [comment]
Thanks!

IMO, I don't think this fix is correct. And perhaps it should be reverted.

The example I used, `form_tag`, was a custom template tag. It is not builtin to Django nor a part of a third party library. It was just an example to trigger the bug.

I'm guess if you modify the tag slightly the bug will still exist. For example: `{% formtag foo %}`.

I think a better solution would be to add identifier boundaries to the regexps. I'll see if I can find some time to experiment with this solution.
