### ISSUE TITLE
How to get started

### ISSUE THREAD

**Issue by b0ris0v** [davidmiller/pony-mode#87]
I have installed and configure "pony", like this:
(require 'python-django)
(add-to-list 'load-path "~/.emacs.d/pony-mode/src")
(require 'pony-mode)

What do I need run it in emacs? (M-x ______ ?)

**Comment by davidmiller** [comment]
Hi @b0ris0v, 

The elements in square brackets next to the features list in the README are the pre-bound keyboard shortcuts. 
The interactive functions are in the pony namespace, so M-x pony TAB will give you a list. 

Note - have fixed a number of bugs this AM so you may want to refresh from github master.

Do shout if you have further issues.
Best
