### ISSUE TITLE
manage commands do not work

### ISSUE THREAD

**Issue by jeltoesolnce** [davidmiller/pony-mode#88]
I have created .dir-locals, "C-c C-p g s" works, "C-c C-p !" and other not.

I got this error:
```
     raise TypeError("relative imports require the 'package' argument")
     TypeError: relative imports require the 'package' argument
```

**Comment by davidmiller** [comment]
Hi @jeltoesolnce yep - I'm looking into this now. Should have a patch soon!

**Comment by davidmiller** [comment]
Hi @jeltoesolnce this was related to issues locating .dir-locals.el settings fixed for #73 

Is now working for me with the .dir-locals.el format documented in the project README now, and the latest master - can you re-test ?

**Comment by jeltoesolnce** [comment]
Hi, @davidmiller , all works fine, thank you).

**Comment by davidmiller** [comment]
Great !
